# To auto-connect to Wi-Fi
#CIRCUITPY_WIFI_SSID="@PHICOMM_00"
#CIRCUITPY_WIFI_PASSWORD="delin2016"
CIRCUITPY_WIFI_SSID="DESKTOP-18"
CIRCUITPY_WIFI_PASSWORD="12345678"
#CIRCUITPY_WIFI_SSID="iPhone"
#CIRCUITPY_WIFI_PASSWORD="12345678"

# To enable the web workflow. Change this too!
# Leave the User field blank in the browser.
CIRCUITPY_WEB_API_PASSWORD="q"

CIRCUITPY_WEB_API_PORT=80
CIRCUITPY_WEB_INSTANCE_NAME=""